component: scf
name: dbCommand
inputs:
  handler: index.main
  description: 图书数据分析云函数，包含聚合操作示例
  runtime: Nodejs18.15
  memorySize: 256
  installDependency: true
  timeout: 20
  vpcConfig:
    vpcId: ""
    subnetId: ""
  environment:
    variables: {}
  events: []
  layers: []
  initTimeout: 65
  protocolParams: null
  protocolType: ""
  eip: false
  publicAccess: true
